### ISSUE TITLE
Info on pretraining dataset

### ISSUE THREAD

**Issue by albusdemens** [kiyoungkim1/LM-kor#1]
Hello, thanks for the repo! Is the pretraining dataset available somewhere?

**Comment by kiyoungkim1** [comment]
Pre-training models are available with huggingface library, but data used for pre-training is not released to the "public".

If you wanna find Korean dataset, use [Korpora](https://github.com/ko-nlp/Korpora)

**Comment by albusdemens** [comment]
Thanks for the hint and for letting me know!
