### ISSUE TITLE
어떻게 쓰는거죠? 그대로 복사해서 붙여넣고 print를 하나요?

### ISSUE THREAD

**Issue by sickkal** [kiyoungkim1/LM-kor#2]
from transformers import BertTokenizerFast, GPT2LMHeadModel
tokenizer_gpt3 = BertTokenizerFast.from_pretrained("kykim/gpt3-kor-small_based_on_gpt2")
input_ids = tokenizer_gpt3.encode("text to tokenize")[1:]  # remove cls token
        
model_gpt3 = GPT2LMHeadModel.from_pretrained("kykim/gpt3-kor-small_based_on_gpt2")

사용법이 어떻게 되나요?

**Comment by kiyoungkim1** [comment]
레포의 [GPT3 generation notebooks](https://colab.research.google.com/github/kiyoungkim1/LMkor/blob/main/notebooks/gpt3_text_generation.ipynb)를 참고해주세요.
