### ISSUE TITLE
mask_prediction 관련 문의

### ISSUE THREAD

**Issue by ByungjunKim** [kiyoungkim1/LM-kor#4]
안녕하세요 좋은 모델 만들어주셔서 감사합니다.

만들어주신 mask_prediction 함수로 한국어 문장의 맨마지막 종결어를 맞추는 모델을 만들었는데요.

질문이 있습니다.

1. 종결어 '다'를 넣었을때의 변화
아래 처럼 종결어 '다'를 넣으면 제가 예상한 정답인 '믿다'가 나오는데요.
이게 '다'를 넣어서 학습함으로써 연산량이 줄기때문에 그런것인가요?

![image](https://user-images.githubusercontent.com/7889473/190363113-1c4b97c5-1c9d-4c05-9ba8-d485c77b6946.png)

2. 그리고 fill-mask task는 성능 지표가 있는지 궁금합니다.
네이버 영화평 처럼 긍부정 분류하는 모델은 보편적인데 fill-mask(mask_prediction)은 찾기가 어렵더군요.

좋은 모델 만들어 주셔서 감사합니다.

김병준 드림.

**Comment by kiyoungkim1** [comment]
안녕하세요.

먼저,
언어모델을 학습하기 위해서 문장을 특정단위(token)으로 끊게 됩니다.

해당 부분에 대해서는 다음 영상을 참고해 주세요: https://youtu.be/Z201jwWo-xs?t=1780

mask는 이 중 한 token을 예측하는 것입니다.
제가 학습한 wordpiece로 tokenizing을 했을 때 '믿다'를 '믿, 다'로 2개로 분절해 연산한다면 mask에서 '믿다'라는게 나올 수 없습니다. mask는 하나의 token만 예측하기 때문입니다.

따라서 첫번째 태스크인 '이 나라는 불교를 mask.'의 경우 '믿다'보다 여러 종결어미들이 추천된 것 같습니다. 이는 tokenizing하는 방법에 따라 결과가 달라 질 수 있고, 만약 단어사전에 '믿다'라는 token이 있는 경우 '믿다'로 예측할 수도 있을 것입니다.

다음,
fill-mask task는 모델을 학습할 때 쓰는 task(masked language model)이며 따로 성능지표는 없습니다.
예를들어 '이 나라는 불교를 mask.'에서 mask에 들어갈 수 있는 단어는 여러 개가 될 것입니다. 복수의 정답이 있는 경우 task로 하기는 적합하지 않다고 생각됩니다. 다만 학습을 할 때는 이러한 복수의 정답 중 어떤 것들이 확률적으로 많이 나타나는지 아닌지를 학습하기 때문에 많이 활용하고 있습니다.

좋은 연구 하십시오.
감사합니다!

**Comment by ByungjunKim** [comment]
감사합니다. 연구에 큰 도움이 되었습니다.
저는 NLP를 주로 활용하는 디지털인문학 연구자입니다.
논문에서 김기영님의 모델을 활용하게 되면 꼭 인용하겠습니다.

**Comment by ByungjunKim** [comment]
혹시 만드신 모델에 제가 가진 데이터를 Fine-Tuning 하는 코드가 따로 있을까요?

**Comment by kiyoungkim1** [comment]
fine-tuning을 하려고 하는 task가 무엇인지에 따라 다를것 같습니다.
가장 간단한 sequence_classificatio의 경우 아래에서 colab으로 가능하니 확인 해보셔요.
https://github.com/kiyoungkim1/ReadyToUseAI

디지털인문학이라니 어떤 분야인지 궁금합니다.
저희도 텍스트에 관심이 많은데 서울에 오실 일이 있으시면 한번 구경 오시겠어요?
간단한 부분은 도움 드릴 수도 있을 것 같습니다.

kykim@artificial.sc로 메일 주시길 부탁드립니다.
